abiturient2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from main.views import *
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^application/', include('form.urls')),
    url(r'^kladr/', include('kladr.urls')),
    url(r'^education/', include('education.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tiles/', include('tiles.urls')),
    url(r'^media/(?P<path>.*)$', mediaserver),
)

form/urls.py
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
    url(r'^add/$', form),
    url(r'^edit/(?P<id>\d+)/$', form),
    url(r'^list/$', app_list),
)

form/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from kladr.models import *

class UnicodeIsNameMixin(object):
    def __unicode__(self):
        return self.name

class IDSocialStatus(models.Model, UnicodeIsNameMixin):
    name = models.CharField(max_length=255)


    class Meta:
        verbose_name = 'социальный статус'
        verbose_name_plural = 'социальные статусы'


class Nationality(models.Model, UnicodeIsNameMixin):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'национальность'
        verbose_name_plural = 'национальности'


class MilitaryStatus(models.Model, UnicodeIsNameMixin):
    name=models.CharField(max_length=255)

    class Meta:
        verbose_name = 'военная служба'
        verbose_name_plural = 'военные службы'


class Language(models.Model, UnicodeIsNameMixin):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'иностранный язык'
        verbose_name_plural = 'иностранные языки'

class Citizenship(models.Model, UnicodeIsNameMixin):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'гражданство'
        verbose_name_plural = 'гражданства'


class Application(models.Model):
    GENDER=(
        (1,'Мужской'),
        (2,'Женский'),
    )

    #Персональная информация
    Edited          = models.BooleanField(default=False)
    user            = models.OneToOneField(User, verbose_name='Пользователь', null=True, blank=True)
    LastName        = models.CharField(max_length=255,  blank=True, verbose_name='Фамилия')
    FirstName       = models.CharField(max_length=255,  blank=True, verbose_name='Имя')
    MiddleName      = models.CharField(max_length=255,  blank=True, verbose_name='Отчество')
    BirthDay        = models.DateField(                 blank=True, null=True, verbose_name='Дата рождения')
    IDSex           = models.PositiveSmallIntegerField( blank=True, null=True, choices=GENDER, verbose_name='Пол')
    IDSocialStatus  = models.ForeignKey(IDSocialStatus, blank=True, null=True, verbose_name='Социальный статус')
    Nationality     = models.ForeignKey(Nationality,    blank=True, null=True, verbose_name='Национальность')
    Citizenship     = models.ForeignKey(Citizenship,    blank=True, null=True, verbose_name='Гражданство')

    #Паспортные данные
    PassportSer     = models.CharField(max_length=4, blank=True, null=True, verbose_name='Серия паспорта')
    PassportNumb    = models.CharField(max_length=6, blank=True, null=True, verbose_name='Номер паспорта')
    CodUVD          = models.CharField(max_length=7,    blank=True, null=True, verbose_name='Код подразделения УВД')
    PassportDate    = models.DateField(                 blank=True, null=True, verbose_name='Дата выдачи паспорта')
    BirthPlace      = models.CharField(max_length=255,  blank=True, verbose_name='Место рождения')
    PassportIssued  = models.CharField(max_length=255,  blank=True, verbose_name='Паспорт выдан')

    #Паспортные данные иностранного гражданина
    ForeignPassportSer    = models.CharField(max_length=255, blank=True, null=True, verbose_name='Серия паспорта')
    ForeignPassportNumb   = models.CharField(max_length=255, blank=True, null=True, verbose_name='Номер паспорта')
    ForeignPassportDate   = models.DateField(                 blank=True, null=True, verbose_name='Дата выдачи паспорта')
    ForeignBirthPlace     = models.CharField(max_length=255,  blank=True, verbose_name='Место рождения')
    ForeignPassportIssued = models.CharField(max_length=255,  blank=True, verbose_name='Паспорт выдан')


    RegCountry = models.ForeignKey(Country, blank=True, null=True, verbose_name='Страна')
    RegRegion = models.ForeignKey(Region, blank=True, null=True, verbose_name='Регион')
    RegDistrict = models.ForeignKey(District, blank=True, null=True, verbose_name='Район')
    RegCity = models.ForeignKey(City, blank=True, null=True, verbose_name='Город')
    RegStreet = models.ForeignKey(Street, blank=True, null=True, related_name='+', verbose_name='Улица')
    RegHouse = models.CharField(max_length=255, blank=True, null=True, verbose_name='Дом')
    RegApartment = models.CharField(max_length=255, blank=True, null=True, verbose_name='Квартира')
    RegZipcode = models.IntegerField(max_length=6, blank=True, null=True, verbose_name='Почтовый индекс')

    ResEqualsReg = models.BooleanField(default=True, verbose_name='Прописка и адрес фактического проживания совпадают')

    #Ulyanovsk-city only
    ResStreet = models.ForeignKey(Street, blank=True, null=True, related_name='+', verbose_name='Улица')
    ResHouse = models.CharField(max_length=255, blank=True, null=True, verbose_name='Дом')
    ResApartment = models.CharField(max_length=255, blank=True, null=True, verbose_name='Квартира')
    ResZipcode = models.IntegerField(max_length=6, blank=True, null=True, verbose_name='Почтовый индекс')

    Fives  = models.IntegerField(verbose_name='количество пятёрок', default=0)
    Fours  = models.IntegerField(verbose_name='количество четвёрок', default=0)
    Threes = models.IntegerField(verbose_name='количество троек', default=0)

    def __unicode__(self):
        return "%s %s %s" % (self.LastName, self.FirstName, self.MiddleName)

    def certificate_mean(self):
        return (self.Fives * 5 + self.Fours * 4 + self.Threes * 3)/(self.Fives + self.Fours + self.Threes)


class ExamName(models.Model, UnicodeIsNameMixin):
    name = models.CharField(max_length=255)


class Exam(models.Model):
    Number   = models.CharField(max_length=20, blank=True, verbose_name='Номер свидетельства ЕГЭ')
    ExamName = models.ForeignKey(ExamName,     blank=True, null = True, verbose_name='Название экзамена')
    Mark     = models.IntegerField(            blank=True, null = True, verbose_name='Оценка')
    DocSer   = models.CharField(max_length=4,  blank=True, null = True, verbose_name='Серия паспорта')
    DocNum   = models.CharField(max_length=6,  blank=True, null = True, verbose_name='Номер паспорта')
    application = models.ForeignKey(Application)

    def __unicode__(self):
        return self.Number

    class Meta:
        verbose_name = 'свидетельство ЕГЭ'
        verbose_name_plural = 'свидетельства ЕГЭ'

form/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.forms.widgets import RadioSelect, TextInput, Select, DateInput
from django.forms.models import inlineformset_factory, modelformset_factory

from kladr.models import *
from kladr.forms import FormKLADRRelatesMixin

from models import Application, Exam
from widgets import ChainedSelectWidget, ChainedTextWidget, SelectWidget

disabled = {'disabled': 'disabled'}


def get_object_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


class DependentFormMixin(object):
    def _prepare_dependent_fields(self, fields, parent, parent_id, value=''):
        for f in fields:
            self.fields[f].widget.attrs.update({
                'data-dependent-field': parent_id,
                'data-dependent-value': str(value),
                'class': '%s %s' % (self.fields[f].widget.attrs['class'], 'dependent')
                if 'class' in self.fields[f].widget.attrs
                else 'dependent'
            })
            value_is_forbidden = parent is None or\
                                 (value == '' and parent == '') or\
                                 (value != '' and parent.pk != value)
            if value_is_forbidden:
                self.fields[f].widget.attrs.update(disabled)

            # def field_clean_template():
            #     if value_is_forbidden:
            #         return None
            #
            # self.__setattr__('clean_%s' % f, field_clean_template)

    def field_cleaner(self, field_name, parent_field_name, model, parent_model):
        if field_name in self._errors:
            elem = model.objects.get(pk=self.data[field_name])
            parent = parent_model.objects.get(pk=self.data[parent_field_name])
            if elem and parent and elem.id.startswith(parent.id):
                self.cleaned_data[field_name] = elem
                del self._errors[field_name]


class FormRelatesMixin(object):
    def _prepare_form_relation(self, field, rel_field, parent_field, model):
        # Если родитель пустой, то детей не грузим и выключаем поле
        if not hasattr(self.instance, parent_field):
            self.fields[field].widget.attrs.update({'disabled': 'disabled'})
            self.fields[field].queryset=model.objects.none()
        else:
            parent = self.instance.__getattribute__(parent_field)
            # Иначе грузим детей только этого родителя
            self.fields[field].queryset=model.objects.filter(**{rel_field: parent})


class PersonalApplicationForm(ModelForm, DependentFormMixin):
    class Meta:
        model = Application
        widgets = {
            'IDSex': RadioSelect()
        }
        fields = ['LastName', 'FirstName', 'MiddleName', 'BirthDay', 'BirthPlace', 'IDSex',
                  'IDSocialStatus', 'Nationality', 'Citizenship',
                  'PassportSer', 'PassportNumb', 'CodUVD', 'PassportDate', 'PassportIssued',
                  'ForeignPassportSer', 'ForeignPassportNumb', 'ForeignPassportDate', 'ForeignPassportIssued']

    def __init__(self, *args, **kwargs):
        super(PersonalApplicationForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].empty_label = ''
            if type(self.fields[f].widget) in (TextInput, Select, DateInput, SelectWidget):
                self.fields[f].widget.attrs.update({'class':'form-control'})

        # citizenship_russia_data = {
        #     'parent': self.instance.Citizenship,
        #     'parent_id': 'id_Citizenship',
        #     'value': 1
        # }
        # citizenship_dependent_fields = [
        #     'PassportSer',
        #     'PassportNumb',
        #     'CodUVD',
        #     'PassportDate',
        #     'PassportIssued'
        # ]
        # self._prepare_dependent_fields(citizenship_dependent_fields, **citizenship_russia_data)


class ResidenceApplicationForm(ModelForm, DependentFormMixin, FormKLADRRelatesMixin):
    class Meta:
        model = Application

        fields = ['RegCountry', 'RegRegion', 'RegDistrict', 'RegCity', 'RegStreet', 'RegHouse',
                  'RegApartment', 'RegZipcode', 'ResEqualsReg',
                  'ResStreet', 'ResHouse', 'ResApartment', 'ResZipcode']

        widgets = {
            'RegDistrict': ChainedSelectWidget(
                parent_name='RegRegion',
                url='/kladr/districts/',
            ),

            'RegCity': ChainedTextWidget(
                parent_name='RegDistrict',
                url='/kladr/cities/',
            ),

            'RegStreet': ChainedTextWidget(
                parent_name='RegCity',
                url='/kladr/streets/',
            ),

            'ResStreet': ChainedTextWidget(
                url='/kladr/streets/01000001000/',
            ),
        }

    def __init__(self, *args, **kwargs):
        super(ResidenceApplicationForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].empty_label = ''
            if type(self.fields[f].widget) in (TextInput, Select, DateInput, SelectWidget, ChainedTextWidget, ChainedSelectWidget):
                self.fields[f].widget.attrs.update({'class':'form-control'})

        # КЛАДРовые связи регионов, районов, городов и улиц
        if self.instance:
            self._prepare_KLADR_form_relation('RegDistrict', self.instance.RegRegion, District)
            self._prepare_KLADR_form_relation('RegCity', self.instance.RegDistrict, City)
            self._prepare_KLADR_form_relation('RegStreet', self.instance.RegCity, Street)

        # Улицы только города Ульяновска
        # TODO: Вынести id Ульяновска в КЛАДРе в настройки
        self.fields['ResStreet'].queryset=Street.objects.filter(id__startswith='01000001000')

        # Показывать регионы только если выбрана Россия
        self._prepare_dependent_fields(['RegRegion'], self.instance.RegCountry, 'id_RegCountry', 1)

        # Дом, квартира и индекс активируются только если выбран город
        city_non_empty_data = {'parent': self.instance.RegCity, 'parent_id': 'id_RegCity'}
        city_non_empty_fields = ['RegHouse', 'RegApartment', 'RegZipcode']
        self._prepare_dependent_fields(city_non_empty_fields, **city_non_empty_data)

    def clean(self):
        super(ResidenceApplicationForm, self).clean()
        self.field_cleaner('RegDistrict', 'RegRegion', District, Region)
        self.field_cleaner('RegCity', 'RegDistrict', City, District)
        self.field_cleaner('RegStreet', 'RegCity', Street, City)

        if 'ResEqualsReg' in self.data:
            self.cleaned_data['ResStreet'] = None
            self.cleaned_data['ResHouse'] = None
            self.cleaned_data['ResApartment'] = None
            self.cleaned_data['ResZipcode'] = None
        return self.cleaned_data


class ExamForm(ModelForm):
    class Meta:
        model = Exam
        exclude = ['application']

    def __init__(self, *args, **kwargs):
        super(ExamForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].empty_label = ''
            if type(self.fields[f].widget) in (TextInput, Select, DateInput, SelectWidget, ChainedTextWidget, ChainedSelectWidget):
                self.fields[f].widget.attrs.update({'class':'form-control'})

ExamFormSet = inlineformset_factory(Application, Exam, form=ExamForm, extra=1, max_num=5)


class CertificateForm(ModelForm):
    class Meta:
        model = Application
        fields = ['Fives', 'Fours', 'Threes']

    def __init__(self, *args, **kwargs):
        super(CertificateForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].empty_label = ''
            if type(self.fields[f].widget) in (TextInput, Select, DateInput, SelectWidget):
                self.fields[f].widget.attrs.update({'class':'form-control'})

form/views.py
# -*- coding: utf-8 -*-
from django.template import loader, Context, RequestContext, Template
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, redirect
from models import *
from forms import *
from education.forms import EducationFormSet


def get_forms(kwargs):
    return {
        'personal_form': PersonalApplicationForm(**kwargs),
        'residence_form': ResidenceApplicationForm(**kwargs),
        'certificate_form': CertificateForm(**kwargs),
    }


def get_formsets(kwargs):
    return {
        'exam_formset': ExamFormSet(**kwargs),
        'edu_formset': EducationFormSet(**kwargs),
    }


def are_valid(forms):
    for f in forms:
        if not forms[f].is_valid():
            return False
    return True


def app_list(request):
    applications = Application.objects.all()
    t = loader.get_template('form/list.html')
    c = RequestContext(request, {'applications': applications})
    return HttpResponse(t.render(c))


def render_form(request, context):
    t = loader.get_template('form/main.html')
    c = RequestContext(request, context)
    return HttpResponse(t.render(c))


def get_instance_and_url(request, id):
    if id is None:
        return Application.objects.create()
    else:
        return get_object_or_404(Application, pk=id)


def form(request, id=None):
    instance = get_instance_and_url(request, id)
    url = request.path
    context = {'id': id, 'url': url}
    if request.method == 'POST':
        kwargs = {'instance': instance, 'data': request.POST}
        forms = get_forms(kwargs)
        formsets = get_formsets(kwargs)

        if are_valid(forms) and are_valid(formsets):
            for f in forms:
                forms[f].save()
            for f in formsets:
                formsets[f].save()
            return redirect(url)
        else:
            context.update(forms)
            context.update(formsets)
            return render_form(request, context)
    else:
        kwargs = {'instance': instance}
        context.update(get_forms(kwargs))
        context.update(get_formsets(kwargs))
        return render_form(request, context)

main/views.py
# -*- coding: utf-8 -*-
from django.views.static import serve
from django.conf import settings

def mediaserver(request, path):
    return serve(request, path, settings.MEDIA_ROOT)

form/templates/form/exam_formset_item.html
<div data-formset-form class="data-formset-form">

    {% with input=form.Number %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.ExamName %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.Mark %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.DocSer %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.DocNum %}{% include 'form/form-group.html' %}{% endwith %}
    {{ form.id }}
    <span class="hidden">{{ form.DELETE }}</span>
    <a data-formset-delete-button class="data-formset-delete-button"><span class="glyphicon glyphicon-remove"></span></a>
</div>

form/templates/form/form-group.html
<div class="form-group">
    <label class="common-form-label" for="{{ input.auto_id }}">{{ input.label }}</label>
    <div class="form-control-container">{{ input }}</div>
</div>

form/templates/form/formset-container.html
<div id="{{ formset_id }}" class="entry" data-formset-prefix="{{ formset.prefix }}">
    {{ formset.management_form }}
    <div data-formset-body>
        {% for form in formset.forms %}{% include formset_template %}{% endfor %}
    </div>
    <script type="form-template" data-formset-empty-form>
        {% with form=formset.empty_form %}
            {% include formset_template %}
        {% endwith %}
    </script>
    <input type="button" value="Добавить" data-formset-add>
</div>

form/templates/form/list.html
{% extends 'base.html' %}
{% block content %}
<table>
{% for a in applications %}
<tr><td>{{ a.LastName }}</td><td>{{ a.FirstName }}</td><td>{{ a.MiddleName }}</td><td><a href="/application/edit/{{ a.id }}/">Редактировать</a></td></tr>
{% endfor %}
</table>
<a href="/application/add/">Добавить</a>
{% endblock %}

form/templates/form/main.html
{% extends 'base.html' %}
{% block content %}
    <ul class="nav nav-tabs">
        <li class="active"><a href="#personal" data-toggle="tab">Персональная информация</a></li>
        <li><a href="#registration" data-toggle="tab">Место жительства</a></li>
        <li><a href="#education" data-toggle="tab">Образование</a></li>
        <li><a href="#specialities" data-toggle="tab">Специальности</a></li>
    </ul>

    <form action="{{ url }}" method="POST" id="contacts_form">
    <div class="tab-content">
        <div class="tab-pane active" id="personal">
            <h2>Персональная информация</h2>
            {% with input=personal_form.LastName %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.FirstName %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.MiddleName %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.BirthDay %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.BirthPlace %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.IDSex %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.IDSocialStatus %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.Nationality %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=personal_form.Citizenship %}{% include 'form/form-group.html' %}{% endwith %}

            <div id="citizenship-russia-block" {% if not personal_form.Citizenship.value or personal_form.Citizenship.value != 1 %} style="display:none;"{% endif %}>
                {% with input=personal_form.PassportSer %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.PassportNumb %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.CodUVD %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.PassportDate %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.PassportIssued %}{% include 'form/form-group.html' %}{% endwith %}
            </div>

            <div id="citizenship-not-russia-block" {% if not personal_form.Citizenship.value or personal_form.Citizenship.value == 1 %} style="display:none;"{% endif %}>
                {% with input=personal_form.ForeignPassportSer %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.ForeignPassportNumb %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.ForeignPassportDate %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=personal_form.ForeignPassportIssued %}{% include 'form/form-group.html' %}{% endwith %}
            </div>

        </div>
        <div class="tab-pane" id="registration">
            <h2>Место жительства</h2>
            <h3>Прописка</h3>
            {% with input=residence_form.RegCountry %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegRegion %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegDistrict %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegCity %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegStreet %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegHouse %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegApartment %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=residence_form.RegZipcode %}{% include 'form/form-group.html' %}{% endwith %}

            <div class="form-group">
                <label class="checkbox-form-label" for="{{ residence_form.ResEqualsReg.auto_id }}">
                    {{ residence_form.ResEqualsReg }}{{ residence_form.ResEqualsReg.label }}</label>
            </div>

            <div id="residence-block" {% if residence_form.ResEqualsReg.value %} style="display:none;"{% endif %}>
                <h3>Адрес фактического проживания</h3>
                <p>Только для лиц, проживающих в городе Ульяновске</p>
                {% with input=residence_form.ResStreet %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=residence_form.ResHouse %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=residence_form.ResApartment %}{% include 'form/form-group.html' %}{% endwith %}
                {% with input=residence_form.ResZipcode %}{% include 'form/form-group.html' %}{% endwith %}
            </div>
        </div>
        <div class="tab-pane" id="education">
            <h2>Образование</h2>
            <h3>Результаты ЕГЭ</h3>
            {% with formset=exam_formset formset_id='exam_formset' formset_template='form/exam_formset_item.html' %}
                {% include 'form/formset-container.html' %}
            {% endwith %}
            <h3>Школьный аттестат</h3>
            {% with input=certificate_form.Fives %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=certificate_form.Fours %}{% include 'form/form-group.html' %}{% endwith %}
            {% with input=certificate_form.Threes %}{% include 'form/form-group.html' %}{% endwith %}
            <p>Средний балл: <span id="certificate_mean">0</span></p>
        </div>
        <div class="tab-pane" id="specialities">
            <h2>Специальности</h2>
            {% with formset=edu_formset formset_id='edu_formset' formset_template='form/spec_formset_item.html' %}
                {% include 'form/formset-container.html' %}
            {% endwith %}
        </div>
    </div>

    {% if id %}<input type="hidden" name="id" value="{{ id }}" />{% endif %}
    <input type="hidden" id="fresh_page" name="fresh_page" value="1" />
    {% csrf_token %}
     <input type="submit" value="Отправить">
    </form>
{% endblock %}

{% block js %}

    <script src="{{ STATIC_URL }}js/jstorage.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.formset.js"></script>
    <script src="{{ STATIC_URL }}packages/jquery-ui/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="{{ STATIC_URL }}js/delayed_fill.js"></script>
    <script src="{{ STATIC_URL }}js/tFormer.min.js"></script>
    <script>
        $(function(){
            $("#exam_formset").formset();
            $("#edu_formset").formset();

            $('#id_ResEqualsReg').on('click', function(){
                var display = this.checked;
                $('#residence-block').css('display',((display)?'none':'block'));
            });

            $('#id_Citizenship').on('change', function(){
                var selected = !!this.value;
                var russia = this.value == 1;
                $('#citizenship-russia-block').css('display',((selected && russia)?'block':'none'));
                $('#citizenship-not-russia-block').css('display',((selected && !russia)?'block':'none'));
            });

            $('#id_Fives, #id_Fours, #id_Threes').on('change keyup', function(){
                calculate_certificate_mean();
            });

            function calculate_certificate_mean(){
                var fives = parseInt($('#id_Fives').val());
                var fours = parseInt($('#id_Fours').val());
                var threes = parseInt($('#id_Threes').val());
                var mean = 0;

                if (fives+fours+threes != 0)
                    mean = (fives*5+fours*4+threes*3)/(fives+fours+threes);
                else mean = 0;
                $('#certificate_mean').html(mean.toFixed(1));
            }

            calculate_certificate_mean();
        });
    </script>

    <script>var my_form_id = new tFormer('contacts_form');
    </script>
{% endblock %}

{% block title %}Basic Formset (Table layout){% endblock %}


{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}packages/jquery-ui/themes/bootstrap/jquery-ui-1.10.0.custom.css">
<style type="text/css">
    span.hidden{
        display: none;
    }

    div.data-formset-form{
        padding: 20px;
    }

    a.formset-button{
        font-size: 28pt;
        cursor: pointer;
        position: absolute;
        text-align: center;
    }

    a.data-formset-delete-button{
        color: #D16165;
        top: 20px;
        right: 20px;
    }

    a.data-formset-up-button{
        color: green;
        top: 80px;
        right: 20px;
    }

    a.data-formset-down-button{
        color: green;
        top: 140px;
        right: 17px;
    }

    .data-formset-form.display.first .data-formset-down-button{
        top: 80px;
        display: block;
    }
    .data-formset-form.display.first .data-formset-up-button{
        display: none;
    }

    .data-formset-form.display.last .data-formset-up-button{
        top: 80px;
        display: block;
    }
    .data-formset-form.display.last .data-formset-down-button{
        display: none;
    }


    label.common-form-label:after{
        content: ':';
    }

    label.common-form-label{
        font-weight: 400;
    }

    input[type=text].error{
        border-color: red;
    }

    .form-control{
        max-width:400px;
    }

    .form-group{
        clear: both;
        margin-bottom: 10px;
    }

    .data-formset-form{
        border: 1px solid rgb(128, 128, 128);
        margin-bottom: 15px;
        padding: 15px;
        position: relative;
    }
</style>
{% endblock %}

form/templates/form/spec_formset_item.html
<div data-formset-form class="data-formset-form display">
    {% with input=form.direction %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.faculty %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.education_form %}{% include 'form/form-group.html' %}{% endwith %}
    {% with input=form.stream %}{% include 'form/form-group.html' %}{% endwith %}
    {{ form.order }}
    {{ form.id }}
    <span class="hidden">{{ form.DELETE }}</span>
    <a data-formset-delete-button class="data-formset-delete-button formset-button"><span class="glyphicon glyphicon-remove"></span></a>
    <a data-formset-up-button class="data-formset-up-button formset-button"><span class="glyphicon glyphicon glyphicon-arrow-up"></span></a>
    <a data-formset-down-button class="data-formset-down-button formset-button"><span class="glyphicon glyphicon glyphicon-arrow-down"></span></a>
</div>